name: Sign Petition
on:
  issue_comment:
    types: [created]

jobs:
  build:
    name: Sign Petition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: jeffrafter/sign-action@v1
        with:
          file-to-sign: README.md
          issue-number: 1
          alphabetize: yes
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
